name: ML Ops CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # For additional testing if needed
    
    - name: Verify model loading
      run: |
        python -c "from joblib import load; model = load('model.pkl'); print(f'Model {type(model).__name__} loaded successfully')"
    
    - name: Run API tests
      run: |
        # Start server in background
        uvicorn app:app --host 0.0.0.0 --port 8000 > server.log 2>&1 &
        SERVER_PID=$!
        
        # Wait for server to start
        sleep 5
        
        # Test prediction endpoint
        RESPONSE=$(curl -s -X POST "http://localhost:8000/predict" \
          -H "Content-Type: application/json" \
          -d '{"sepal_length":5.1,"sepal_width":3.5,"petal_length":1.4,"petal_width":0.2}')
        
        echo "API Response: $RESPONSE"
        
        # Validate response
        python -c "
        import json, sys;
        response = json.loads('$RESPONSE')
        assert 'prediction' in response, 'Missing prediction key'
        assert isinstance(response['prediction'], int), 'Prediction should be integer'
        print('Response validation passed')
        "
        
        # Kill server
        kill $SERVER_PID
        
        # Check server logs for errors
        cat server.log